### ISSUE TITLE
Additional rounding functions

### ISSUE THREAD

**Issue by calebzulawski** [rust-lang/portable-simd#38]
- [ ] `to_int` (requires comparisons in #36)
- [ ] `rount_to_int` (initially proposed in #23)
- [x] `trunc` (removed in #47)
- [x] `fract` (removed in #47)
- [x] `round` (removed in #47)

`round_to_int` can't be directly implemented in LLVM, since `llvm.lround` doesn't work on vectors.  I'm not sure this function is actually necessary since you can do `x.round().to_int()`.

**Comment by workingjubilee** [comment]
I am working on the PR that restores these.

**Comment by workingjubilee** [comment]
Closed by https://github.com/rust-lang/portable-simd/pull/232.
