### ISSUE TITLE
Expose the `stdsimd` crate as the `core::simd` module (behind a feature flag)

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/portable-simd#7]
We'd want to follow what `stdarch` does here to get itself exported as `core::arch`

**Comment by calebzulawski** [comment]
There are some various steps I think we need to complete before doing this:

- [ ] Review and merge #67 (limiting lanes to 64)
- [ ] Remove `From` splatting implementations (#69)
- [ ] API audit

and then finally:
- [ ] use rust feature flags to limit capability (#70)
- [ ] add to `core` (#7)

Tagging some people for the API audit (anyone else ask and I can add you).  This should probably wait until all of the above issues are resolved.
- [ ] @KodrAus
- [ ] @Lokathor 
- [ ] @workingjubilee 
- [ ] @calebzulawski

**Comment by dvc94ch** [comment]
Anything I can help with? Would be really cool to see this in nightly soon.

**Comment by calebzulawski** [comment]
PR is rust-lang/rust#89167
